### GET request users
GET localhost:8080/entity/users

### GET request user
GET localhost:8080/entity/user/5

### Send POST resquest with json body
POST localhost:8080/entity/users
Content-Type: application/json

{
  "id": "user06",
  "pwd": "pass06",
  "name": "신사임당",
  "enrollAt": "2024-02-29T03:15:45.796+00:00"
}

### PUT modify user
PUT localhost:8080/entity/users/1
Content-Type: application/json

{
  "id": "user07",
  "pwd": "pass07",
  "name": "임꺽정"
}

### GET modified user
GET localhost:8080/entity/user/1

### DELETE remove user
DELETE localhost:8080/entity/users/1