server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          #github? ??? ???? ??, ?? repo? ??? ??? ??.
          #github ??? ????? http://
          uri: file:///C:\lecture\09_msa\config
