server:
  port: 9001

spring:
  application:
    name: swcamp-user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

# jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

# eureka client config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# yml ??? ???? ?? ??
swcamp:
  message: Let's do MSA!

## 토큰 생성을 위한 키 생성
#token:
#
#  # JWT 토큰의 만료시간 설정(ms단위)(여기서는 12시간으로 설정)
#  expiration_time: 43200000
#
#  # JWT 토큰의 verify signature를 위한 secret-key
#  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==

# Actuator 추가 후
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
