spring:
  datasource:
        driver-class-name: org.mariadb.jdbc.Driver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:mariadb://localhost:3306/menudb
#    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/menudb
        username: swcamp
        password: swcamp
#
#logging:
#  config: classpath:log4j2.xml

